travis:
  secure:
    BINSTAR_TOKEN: Xz3HJWlOrhEwsaylSHJqxw2LhjW0IlTOJqtZ5WmAJ80SwSkcx17OfKhSWjsMPnr8wbixaqPqYfAU7TlBDEnQ5q+5JZmTcrWjB7Fy09EzjKSxjED81+KhNCjErw3RIbR6CAV6vSm++Ra6eXe0kVze6GMfd1j94xdcxu+sjYiIFAw5vILlJ0KlGVeBkYCqVW10epfn173TdGjBxDOz9rroo/ZL/t9vIEeT91tE02RdqeReMs0BdyBM6aYAbAA1zP2V/4IyDU4clKqY4RNyySJe12c6DIgrzm/EPc34tkMuJcGT2BpPDd9mc0twjd2xzGm31JYQVMvpfuAubmtNERV+yUJw7+zazBZ93tNlnfn+jpMg2nKDUXiwh8wtcliWs7Dx4i3JagHm4NQy9DwHL+NHEs8V6u3a6pCYFRpUePweki0SjYku7+GkEiSGSnJojWPEidXIkTp95z8/y6oxu6OvO/NTX8d7NZ5fk5rd8tXbNUAarlm62aJWnXKf77TIQCGhf+1m/YBrNtaSv52s/3tJPa8eDCYh6aCSAcfApCb9fhJMMw10aXL5c3lOo/wz4KQ1L4yafsHi7PNa5J8gr2rAehdzR0cdp612YJ5kkplikoHId9CgjCN1o9VRCTDWE22QbDdr/H3elGaeJu7lheZELHbnjxUKpm2yW1vQ7Va5VkA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
