travis:
  secure:
    BINSTAR_TOKEN: wvhU9DoR9RsOXkOoxPeoUFgbgJqAa/zw5vBi6mDSYfJFcFJl9ZXOG2rAwWfkjXt/o2537v9VVaYkIDoWiVZ5vbkioq+tBMTk1TWK+WWXAQHqXBdbNvI18Pf3kykHKyi4Sj5uQ7fnDyLWo2695Trza9a0gQ4yev59+11ISAoGqKRxuBEzvnSfs7iKcxYqABCZ4Xgan6yfEYKpj2CzOcTQsoSTgTbzDQMlfICYnIzrNxx8GTtMD1FTKIHYs3ZQw0VFdJeQwgnxA3euSadudFRzv2slYxfU67BPgFJoHNehNhUsSP4AgWJgKN6+0f89MjIrCMtginw9YKn7l96cRxWeJZsO5hvGz6gCwtvLRB0tgjNkMuBihvy2CVWkbMjbY4nTfxx0gXcBfBtLMoxxlumcrdJZvPoQs6tX4I3myIKkoIfj1iPWqA2X2GUrcMbzhcZGt3ZSbbGelj5J+LjlikJHL2Ppl4gKrAoVtXkv8ev895GFUoVOkldbW1HF5M06JPYzVBS0ye0fQJ8GRZkXVCy1Xv+ZtS4NevgPJ7PJXcqCQ8TryLyDuZOfotutw/rU9LWKZCnmAPbO9Ytr+pRxlmdy792LUjSY1vSee2g/oUBOWgkvX4JPIeH1TWMVy/66IfbvRDjz39ofvQRk1FNiQlhqTs3sP5judmtXczB86IVsg1w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
